ARG BASE_IMAGE=registry.fedoraproject.org/fedora:37
FROM $BASE_IMAGE

ARG CLEAN_DNF
RUN true \
    && cmd=(dnf install) \
    && if [ "${CLEAN_DNF}" != "no" ]; then cmd+=("--setopt=keepcache=True"); fi \
    && "${cmd[@]}" -y git gcc /usr/bin/rpmbuild "dnf-command(builddep)" \
    && if [ "${CLEAN_DNF}" != "no" ]; then dnf clean all; fi
RUN mkdir -p -m 0777 /srv/build /usr/local/lib/sources
COPY samba.pamd \
    README.downgrade  \
    samba-master.spec \
    smb.conf.example \
    pam_winbind.conf \
    samba.logrotate  \
    smb.conf.vendor \
    /usr/local/lib/sources
COPY samba-from-source.py /usr/local/bin/samba-from-source.py
ENV INSIDE_CONTAINER=1
RUN /usr/local/bin/samba-from-source.py \
    --skip-build \
    --with-ceph \
    --install-deps-from=/usr/local/lib/sources/samba-master.spec
ENTRYPOINT ["/usr/local/bin/samba-from-source.py"]
